#+TITLE:哲学作业
#+AUTHOR: 秦继豪

* 读<大问题>有感
  人类自从出生开始就不断向周围的人，周围的世界发问。譬如问眼前的东西是什么这样容易解答的问题，实际上只要告诉孩子我们赋予了它什么名字，之后的事情孩子自己就可以探索完成。随着生活时间的增长，很容易就产生生活的意义是什么这个问题。
  生活的意义是什么？我想这个问题很多人都曾经问过自己，它相比于那些诸如“什么是最实在的？”、“宇宙的起源在哪里？”更能引起我们的疑惑和思考。因此解决“生活的意义是什么”也能给我们现阶段生活带来更多的启示。苏格拉低说过，未经审视的生活是不值得过的。那我们每天的生活是什么样的？一天之内来看，起床，吃饭，工作，睡觉。这些是最基本的几个事情，它们之前还会穿插别的事情，譬如娱乐，堵在路上。从一年的时间来看，会有工作，假期。从更长的时间尺度来看，会有换工作，移居别地，抚育孩子等等。越小的时间尺度下，生活会越有规律性，这使得很多人感到厌烦，似乎下一个小时要做的事情是可以完全预见的。于是我们会问自己“生活的意义是什么”。
  让我们来仔细分析一下这五个字，生活的意义。而生活从上面的描述中可以看出其所指十分庞杂。书中拿西班牙语同生活进行比较，若问单词的意义，很容易就回答出其所指，但若是问西班牙语的意义，这个问题就显得没什么用处。同样生活所指甚多，时间就像一根绳子把不同的东西串到一起，这个一串东西我们就称它为生活。想想一下，一个绳子上串有珍珠，贝壳，畸形的石子是不是显得很奇怪。生活就像一个大容器，里面盛满了各种各样的东西，你若问其中东西的意义尚可，你若问容器的意义是什么？除了说盛东西外，其余的意义并不明显。而生活这个词是我们自己创作出来的概念，只是用来指称时间线上的众多事件集合而已，只是称呼上的方便而已。
  若谈到某事的意义，那必定是某事在我们的主观意愿下已经发生了或者我们假想某事已经发生了，由果溯因，我们的主观意愿是什么？想像一下自己的生活是如何发展成现在这个样子的，是不是在无意识的状态下就成了今天这个样子。如果你有清晰的意愿，那你也不会问出生活的意义是什么这个问题了。如果的确如我所说，是在无意识的状态下就成了今天的样子，那再追问生活的意义就如同你随机走过了很多岔路口然后追问自己我是怎么走到这里来的，造成生活现状的原因并不存在，由果溯因的探寻方式就像竹篮打水。因此如果你对生活的意义是什么不能说出自己的答案的话，那就不要再执拗于它。先去给自己的生活定一个意义，然后按照它生活下去吧。

  自我是人们在回忆的时候经常碰到的实体。每个人自我回忆中的主角就是自己，那回忆中的他到底是个什么人呢，为什么感觉如此陌生？在不同的情景下，我们对自己的描述都会不同。太多的描述表明了根本没有触及本质的我，即便这些描述十分正确，但也不能令我们满意。自我认同指的是对本质自我的描述。你可以描述自己身体上的特点，也可以描述自己性格，品质。但是我们貌似总被教导轻视物理特征。在文学作品中经常有某人的朋友变成青蛙了，但我们还认为他是某人的朋友。而另一方面，人的心灵只要发生些许变化，我们就会抱怨他看起来就像是另一个人，或者我们再不认识这个人了。
  自我认同的本质自我就是心灵，这是个非常经典的观点。笛卡尔也是它的支持者，他的观点大概是第一个自我就是本质自我。那哪个是第一个自我呢，是那个正在观察自己的自我，即思考的自我。求自我于心灵会引出一个问题就是，我们如何确定其他自我的存在呢？如果我们同意说，一个人的自我等同于他的意识，我们所能知道的只是自己的意识，那么我们彼此怎样才能超出自我已达他人呢？按照唯我论的观点，除了一个人的心灵，世上别无他物。这里就引出了实在的问题，我们所观察到的他物究竟是真正实在的东西吗？它能否支撑起我们探索的脚步呢？？是否同心灵那样让人感到可靠呢？
  回到之前提到的问题，回忆中的自己到底是谁？实际上这个问题相当于在回忆中的自己和现在的自己的同一性。书中对《人类理解论》的引用对这个问题有有很好的阐述。一个人的同一性就包含在他不间断的生活的每一部分中，通过物质微粒的不断生灭，这种同一性被充满生机地依次统一到同一个有机体中去......人的同一性如果只成立于灵魂的同一性（相当于承认本质自我就是心灵），如果个人的精神不能被统一到不同的身体中去的原因不在于物质的本性，那么那些生活在不同时代、性情各异的人们成为同一个就是有可能的......（一副非常奇异的景象）
  然而，为了找到人格的同一性藏于何处，我们必须考虑人代表什么。在我看来，所谓人就是一种思想者的、有智慧的存在，这种存在有理性、会反思，能在不同的时间和不同的地点确认自己，把自己看作一个能思考的东西；只有通过与思想密不可分的意识，他才能做到这一点。在我看来，这对于思想是本质性的；因为人既然发生知觉，他便不能不知觉到自己是在知觉的。当我们看、听、嗅、尝、感觉、沉思或意欲某种东西时，我们知道自己在做什么。因此，意识永远是和当下的感觉和知觉相伴随的，只有凭借意识，每个人才能成为他所谓的自我。既然意识总是与思想相伴而生，正是意识使每一个人成为他所谓的自我，并且使他与所有其他思想着的东西区分开来，所以个人同一性，即一个理性存在物的同一性，就仅在于意识。而且这个意识在回忆过去的行动或思想时，它追忆到多大程度，个人同一性就达到多大程度。现在的自我就是以前的自我，而且以前反省自我的那个自我，亦就是现在反省自我的这个自我。
