* 可以参考的句子
  语义学，无论是读句子还是写文章，都要逐字地分析。毕竟文字是我们表达自己思想的工具。文字中所包含的东西也是很多的。一个思想和另一个思想的面上交流是通过文字和语言实现的。我所强调的东西是语义学。记得在《计算的本质》中说过计算机是如何确定一条语句的含义？一个是查标准，一个是通过小步语义，大步语义这种较严格的方法，一个是通过一个标准的解释器，那个发明Ruby的日本人写了一个解释器，所有的语义都按照那个解释器来解释。那我们是如何解释别人的话呢？


  方法：当你在思考的时候应该做一些记录，可以是简图，可以是写下来。我建议最好的方式是说一句话，然后用语义学的方法进行分析，对逻辑上的欠缺进行补充，对已有逻辑进行审视修正。对新的可能性进行分支。这样能够得到可靠，可追溯的想法。为什么要做记录呢，还记得有限自动机，带有栈的自动机和图灵机(带有无穷纸带的自动机)吗？其记忆能力决定了他能做的事情。

  方法：并行工程，建立在对全体流程、全体内容的熟悉上。不然并行工程的内容是不完整的，枉论并行工程。

  我们是如何思考的？你在思考的时候是否自己内心中会有一个声音？那么一个先天聋哑的人可以思考吗？实际上是可以的，我们也有用图像思考的能力，你是否会有自己的想法是如何蹦出来的感觉。除了用语言和图像思考的能力，更本质的思考能力是啥？（一个先天聋哑瞎的人）
  
  在考虑某个不熟悉的问题时，别忘了先花相当一段时间梳理一下自己对这个问题的了解，慎重地根据直观提出你认为关键的问题，感兴趣的问题。 在了解的过程中思考这些问题，考察问题是否为真。


  工程上的论文有个特点是，关于应用点的论文，比如加热的方法有很多种，这些想法肯定很早就有论文说了，十几年前就有。然而现在查的话还是有，甚至还算是前沿，这是工程中的一大特点。

  要有尺度的概念，什么样的尺度上什么问题是主要的，影响因素是什么。不同尺度下的模型是不一样的。

  从某种程度上来说，我们不能劝慰我们自己。细想，别人倾诉的烦恼，你可以很清晰地开导他，但是同样的烦恼，我们却不能开导自己。

  事物的发展都是有硬结构和软结构部分的，掌握好硬结构能够建立知识间的联系，软结构能够紧跟潮流。

  细想一下我们是如何思考的，你内心中是否会有一个自言自语的声音。如果你和一个人交流，你如何表达你的思想？答案是很明显的，我们都是在用语言来表达自己的思想，那思想是怎么产生的呢？思想是由语言产生的吗？我觉得一定程度上，思想的确是由语言所引发的，自言自语中总是能够引发新的想法，产生疑惑。我们只能通过语言同自己交流吗(思想只能被语言所表达吗？)很明显不是的，我们在做梦的时候是否会有自言自语的现象呢？会有，但不仅仅是自言自语，还有图像场景，我们也可以通过图像进行思想交流。不过图像由于其太真实了，不可能具有抽象的含义。比如语言中的，本质在图像上就表现不出来。但是图像有个好处就是人脑接受图像的信息更快，接受文字的信息慢，比如你看教学视频就比看书接受的快。
  _因此我们再用书本学习新知识的时候,一定要发明一个方法让自己看书的进度慢下来,比如说做题._
* 摘录的文章
  根据 Kolmogorov的观点，数学是现实世界中的数量关系与空间形式的科学。
 
    (1)因此数学的研究对像是产生于现实中的。然而作为数学加以研究时，必须离开现实的素材（数学的抽象性）。(2)但是，数学的抽象性并不意味着完全脱离于现实素材。需要用数学加以研究的数量关系与空间形式的种类，应科学技术的要求，是不断增加着的。因此上面定义的数学内容在不断地得到丰富。
 
    数学与诸科学：数学的应用是多种多样的，从原理上讲，数学方法的应用范围是无边际的，即物质的所有类型的运动都可以用数学加以研究。但是数学方法的作用与意义在不同情况下是不同的。用单一的模式来包罗现象的所有侧面是不可能的。认识具体的东西（现象）的过程中总是具有下面两个互相缠绕的倾向。
 
   (1)仅将研究对象（现象）的形式分离出来，对这个形式作逻辑上的解析。
   (2)弄清与已经确立的形式所不相符的「现象的方面」，向具有更多的可塑性，更能完整地包含「现象」的新的形式转化。
 
    如果在研究的过程中必须时刻考察现象的本质上新的侧面，因而研究中的困难主要体现在上面的(2)的话。这样的现象的研究（如生物学、经济学、人文科学等）中，数学方法就不是主要的。在这种时候，对现象的所有方面的辨证分析会由于数学形式反而变得含糊。
 
    与此相反，如果用比较简单的、稳定的某种形式便可以把握研究对象（现象），并且在这个形式的范围内产生了在数学上需要加以特殊研究（特别是需要创造新的记号和计算法）的困难而复杂的问题时，这种现象的研究（如物理学）则在数学方法的支配圈内。
 
    做了这些一般性的论述后，首先详细说明了行星运动完全是在数学方法的支配圈内，在这里数学形式是对于有限质点系的牛顿的常微分方程。
 
    从力学转向物理学，数学方法的作用几乎不减，但应用中的困难明显增加。在物理学中，几乎没有不必使用高级数学技术（如偏微分方程理论、泛函分析）的领域。但是研究中出现的困难往往不在于数学理论的推导过程中，而在于「为运用数学所作的假设的选择」和「由数学手段所得结果的解释」中。
 
    数学方法具有包含从考察的某个水平开始，向更高的、本质上新的水平转移这样一个过程的能力。这种例子在物理理论中是可以见到许多的：扩散现象便是一个古典的好例子。从扩散的宏观理论（拋物型偏微分方程）向更高的微观水平的理论（用独立的随机过程来描述溶液中粒子随机运动的统计力学）转移，从后者出发运用大数定律，可导出把握前者的微分方程， Kolmogorov对此种情形作了更加详细具体的说明。
 
    同物理学相比，在生物学中数学更处于从属地位。在经济学和人文科学中的，这种情况就更加突出了，在生物学和杜会科学中数学方法的应用主要是以控制论的形式进行的。在这些学科中，数学的重要性以辅助科学──数理统计学的形式保留几分，但在杜会现象的精确分析中，各个历史阶段中的本质性差异的侧面是占主导地位的，因而数学方法常常要靠边站。
 
    数学与技术、算术、初等几何的原理，正像古代数学史所表明的那样，是从日常生活的需要中产生的。其后的新的数学方法或思想也是受到天文学、力学、物理学等满足实际需要的学科的影响而产生的，但是数学与技术（工程学）的直接联系至今常常是通过已有的数学理论在技术中的应用这样一个形式来实现的。当然还须指出，根据技术上的要求而直接产生新数学的一般理论这种例子也是有的〔例如，最小二乘法（测地），操作数法（电气工程）。作为概率论的新分支的信息论（通信工程），数理逻辑学的新分支，微分方程的近似解法，数值解法等〕。
 
    高度的数学理论使得计算机科学的方法急速地发展起来。而计算机科学在解决原子能利用，宇宙开发中的问题等大量的实际问题时扮演了主要的角色。
 
    Kolmnogorov 在后面的数学史的叙述中也总是注重数学与其它诸学科的关联，同时也高度评价了由于数学内部的要求而推动的纯数学的发展。例如，在实际问题的应用这方面，古代希腊要落后于巴比伦，然而在数学的理论方面，希腊远远领先于巴比伦。他尤其赞颂了「存在无限多个素数」、「等腰直角三角形的斜边与另一边之间不存在公约数」等伟大发现。按着他详细说明了实际主义的巴比伦数学与理想主义的希腊数学是如何经过中世纪的阿拉伯数学，发展至欧洲的近代数学的过程，非常有趣。我从这个历史中学到了许多史实。例如，我以前知道变换群这个概念是在18世纪后半叶至19世纪初，由 Lagrange（分析）、 Galois（方程式论）等有效地使用了的。但我还想知道现在大学里讲授的（抽象）群的定义到底是由谁给出的。根据 Kolmogorov 的数学史，这个定义是由 A. Cayley 在19世纪中叶所给出的。
 
    总之，Kolmogorov 的数学观是由他的数学上的独创性，对于数学应用所抱有的激情及对于数学发展的历史所具有的洞察。这几个方面所组成的，难以用一言来概之。如果一定要用一句话来总结，也许可以这样说：
 
     Kolmogorov把数学看成为可以无限制地成长的「生物体」。
