* 毛胚
  砂型机器造型，公差等级CT8~10,取CT9,80和100对应的公差2.2mm
  根据表2.2-5，加工余量等级为G <-铸造方法
  根据表2.2-4，加工余量为3.0 <-基本尺寸
  毛胚尺寸的偏差是对称分布的83+-1.1，103+-1.1
* 铣47*40平面
  加工余量 3mm，粗铣的经济加工精度为IT12~14，这里取IT12
  查标准IT表，80对应的IT12为0.35mm，因为设计零件中没给最终公差，所以工序尺寸为 \phi 80 0^-0.35
  机床：立式铣床 X52 or X53 看刀柄长度是否合适
  刀具：YG6   \phi 80   寿命180min  齿数z=10

  每齿进给量 f_z=0.14~0.24 取 f_z=0.14  <-  机床功率、刀具材料、工艺系统刚度

  # 看表中的规律，进给量越大，切削速度越慢，转速越慢，进给速度越快
  查表得，v_c=97m/min, n=387r/min, v_f=433mm/min

  查表各个修正系数
  | 项目            | 修正系数 |
  | 有硬皮          |        0.8 |
  | 铸铁硬度        |        1 |
  | 刀具寿命        |        1 |
  | 切削宽度/刀直径 |        1 |
  | 主偏角          |        1 |
  | 齿数之比        |        1 |
  后，v_c=77.6m/min, n=309.6r/min, v_f=346.4mm/min

  查机床规格，选择转速n=300r/min, 进给量v_f=375mm/min

  实际切削速度v_C=\pi d n/1000=75.36m/min
  f_z=v_f/n/10=0.125 mm/z

  综上，机床的工作参数确定，包括主轴转速，工作台进给量。  刀具切削参数确定，包括切削深度，切削宽度，切削速度，每齿进给量。  刀具参数也基本确定，包括材料、直径、齿数、刀片角度、刀具寿命。

  下一步 _校验机床功率_
  根据切削参数，确定功率 1.9kW
  机床效率0.75，P_c=7.5*0.75=5.63kW，完全满足

  计算工时：
  t_m= 47+12/375=0.157min


  请区分 端铣 周铣 立铣 平铣
  概念之间有交叉的
* 钻孔
  拉刀长度760mm
  花键拉削双边余量:0.4~0.5mm
  花键加工经济精度：花键宽0.013，底圆直径0.018。小于图纸要求
  拉削达到的表面粗糙度：3.12~1.6，故对钻孔表面粗糙度要求不高。
  钻->扩 IT 10~11 Ra 12.5~6.3

  所以给拉削留出0.5mm的双边余量
  扩孔留出2mm的双边余量(这个余量是与加工后孔的精度和表面粗糙度有关的),扩孔Ra可达到6.3

  所以
  钻 19.5 扩 21.5 IT 10 Ra=6.3

  机床用z525

  选刀具
  双锥修磨横刃 高速钢
  锥柄麻花钻 d=19.5 切削部分长度l=238,总长估计为 L=378

  选切削用量
  初选进给量f=0.70~0.86mm/r，钻孔深度大于3倍直径加上修正系数0.92，核算表2.8 钻头强度所允许的进给量1.75 没问题。机床所允许的进给量0.93mm/r也没问题，查机床进给量系列，发现0.62
  综上，选择f=0.70*0.92=0.64mm/r=0.62mm/r
  
  刀具寿命，60min
  
  切削速度 初定为18m/min <- 加工材料硬度，进给量，钻头形式，钻头直径。
  修正系数，刀具寿命 k=1,材料硬度 k=1, 钻孔深度 0.85。修正后 15.3m/min

  转速计算，n=249.8r/min。查z525的转速系列，取 n=272r/min 

  校核功率，扭矩52N*m <- 进给量，钻头直径，查表，272转速下，最大扭矩 144.2N*m.
  消耗功率1.1kw <- 材料硬度，钻头直径，切削速度，z525可提供2.8*0.81=2.26kw的功率
  M<M,P<P。没问题！

  计算工时L=l1+l2+l
  l1=D/2*atan(kr)+2, l2=4 l=80
  L=91.7
  t=0.54min

  若 n=195,t=0.8min

  
  
  

  
* 扩孔
  刀具:高速钢整体扩孔钻 定制道具21.5 相邻的只有21.7和22的 k_r=60°
  扩孔钻寿命 T=40min
  
  进给量 f=1mm/r，查阅Z525的进给量，取f=0.81mm/r

  由于扩孔数据较少，采用计算公式法。
  计算得v_c=21.89m/min
  修正系数 k=1 （很多数据缺失，认为k=1）

  机床转速 n=v_c*1000/(3.14*d）=324r/min，选择 250r/min or 351r/min

  机动时间：L=l1+l2+l=2/2*atan(60)+2  +   4   +  80  =86.6mm
  T=L/fn=86.6/(0.81*250)=0.43min
  
* 铣槽
  槽的尺寸大概 7*6

  首先选用铣刀直径 最大直径63mm，宽8mm, z=10

  选择进给量（ 0.01~0.005） *1.3 = 0.013  ~ 0.0065 0.01mm/z

  机床用X62  工作台1250*320  3个T型槽 槽宽18 槽距70

  铣刀标准寿命 T=60min

  计算切削速度，Cv=10.5 qv=0.2 xv=0.2 yv=0.4 uv=0.5 pv=0.1 m=0.15
  计算的 vc= 85.9 m/min,进而得到n=434.2r/min. 查阅X62转速系列取 375r/min。则
  vc=74.2m/min,机床进给量f=37.5mm/min

  计算切学圆周力
  | cf |  xf |   yf |   uf | wf |   qf |
  | 30 | 1.0 | 0.65 | 0.83 |  0 | 0.83 |
  结果是 145N，    铸铁-铸铁摩擦系数0.18    145/0.18=805N
  转矩是 145*20mm=2.9 N*m   摩擦力力矩大概是18.2mm，当量摩擦力大概是需要159N，正压力需要885N。
  # 更正
  vc=74m/min,机床进给量f=37.5mm/min
  铣削力计算
* 拉花键孔
  拉刀总长 760mm
  单面齿升：0.08，拉削速度，4.5~3.5m/min，取4m/min，单面余量zb=2.75

* 粗铣18*23槽
  z=14
  进给量：0.025mm/z
  
* 精铣18*23槽
  fz=0.15mm/z
  切削参数：vc=60m/min n=130r/min f=500mm/min
  得机床转速n=153r/min
  选X62,转速序列取150r/min
  机床进给量，f=0.15*14*150=315mm/min
  查进给量序列，取f=300mm/min
  切削工时，t=124/300=0.41min

* 精铣8*8槽
  每转进给量 0.4~0.6 ，取0.6，每齿进给量0.06mm/z
  标准寿命240.这里寿命180，选择vc=113 n=181 vf=231
  机床转速：n=570r/min，选375r/min，
  则进给量：f=0.6*375=225mm/min,选择f=190mm/min
  切削工时：t=69/190.0=0.36min

  
* 夹具设计
  圆压块规格：
  D=50 H=15 SR=36 
  电机用内六角螺栓 M8
  圆压块 外径50 相配件M8
  压板上圆压块用 开槽盘头螺钉 GB/T 67-2000
  球面垫圈 外径30 内径17 厚度6 GB/T 849-1988
  锥面垫圈 内径20 锥度120°
  压锥面垫圈用M4内六角螺钉 圆柱头直径7mm, 厚度4，
  柄中部球面垫圈 外径37 内径 21 厚度7
  柄中部锥面垫圈 外径37 内径 25 厚度7
  
