* 设备管理具体如何实施？
* 设备管理从层次上来说，分哪几部分？
* 设备管理和设备维修制度的关系？
* 维修方式的选择依据？
  可以根据可靠性理论，对失效后果进行分析，造成严重后果的要进行状态监测，预防维修，那些坏了也没啥事儿的，能迅速修好的可采用事后维修。
  修起来花费高的，要视情维修。
  故障间隔短的，要改进维修
* 不同维修制度的侧重点在哪里？
* 维修规划如何编制？
  1. 根据生产流程＆经验，确定关键工作中心，把设备分成个ABC类
  2. 为不同类的设备选择不同的维修方式
  3. 根据每台设备的维修特点，重要程度，生产安排，编一个细则出来，最终形成整个工作中心、工厂的维修规划。

* 有哪几大损失？
  停机损失
  速度损失
  废品损失

* 维修性怎么度量？
  维修级别，是自己当场修，还是让别人来修，还是搬到厂家修
  维修时间
  也要考虑可靠性模型，什么串联并联模型下不一样。
* 关于维修时间的度量有哪些方式？感觉和维修策略也有一定的关系
  MTTR ： 平均修复时间，指的是坏了修好所需要的时间，事后维修
  修复时间中值：修复时间可能由于备件的延误等各种原因导致MTTR不准，修复时间中值还行
  系统平均停机时间：包括坏了修好所用的时间即MTTR，还有计划性维修所用的时间
  平均恢复时间：MTTR+维修延误时间+供应延误时间
  每工作小时维修工时
* 以XX为中心的维修策略
  这种以XX为中心的维修策略,实际上就是把前面提到的几种维修策略因地制宜的应用.之所以会出现众多的XX,关键就在于这个因地制宜上.不同的人看重点不一样.所以以XX为中心的维修策略,主要的研究内容是啥呢?就是进行量化工作
** 以可靠性为中心的维修策略(RCM)
   建立在对设备的了解上。要对设备进行故障模式及影响分析，对可维修性进行分析。
   比如说，这个零件很容易坏，而且它坏了要修好长时间，影响生产，那可靠性低，可维修性低。
   另一个零件很容易坏，但是很容易修，那可靠性低，可维修性高。
   故障后果又分成什么潜在故障，安全故障，运行故障，非运行故障，这些都是FMEA的正常步骤。
** 费用有效维修(CEM)
   这个就是在RCM的基础上，对各种损失和维修费用进行定量化分析，以费用最少为目标。
   这个费用包括啥呢？有事后维修的费用，有计划性预防维修的费用，预防性维修的收益
* MES和设备管理到底是一个什么关系，包含，并列？
  ERP属于计划层，强调大方向计划的制定，处理各种订单。
  处理销售订单、应收账单、应付账单、采购管理
  产生主生产计划、物料需求计划、采购计划

  MES属于执行层，强调生产过程的动态管理。
  对主生产计划分解，产生车间作业计划：什么时间用什么人和物料生产什么东西。
  重点：产品生产的执行过程，平衡生产能力，跟踪产品。
  生产作业计划、生产调度、设备管理、质量管理、物料跟踪、工艺管理、数据管理、数据分析


* 论文内容、结构问题
  设备故障监测、预测技术
  分类技术:｛模糊理论、ABC、可靠性、分析｝
  1. 备件管理划分方法，ABC，可靠性
  2. 维修策略选择方法
     
  设备资源建模：静态、动态
  
  设备报废
  21 世纪的维修——再制造工程
